/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as _authRouteRouteImport } from './routes/__auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as _authLoginRouteImport } from './routes/__auth/login'
import { Route as DashboardMembersIndexRouteImport } from './routes/dashboard/members/index'
import { Route as DashboardMarriageIndexRouteImport } from './routes/dashboard/marriage/index'
import { Route as DashboardContributionIndexRouteImport } from './routes/dashboard/contribution/index'
import { Route as DashboardConfirmationIndexRouteImport } from './routes/dashboard/confirmation/index'
import { Route as DashboardCommunionIndexRouteImport } from './routes/dashboard/communion/index'
import { Route as DashboardBaptismIndexRouteImport } from './routes/dashboard/baptism/index'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const _authRouteRoute = _authRouteRouteImport.update({
  id: '/__auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const _authLoginRoute = _authLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => _authRouteRoute,
} as any)
const DashboardMembersIndexRoute = DashboardMembersIndexRouteImport.update({
  id: '/members/',
  path: '/members/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardMarriageIndexRoute = DashboardMarriageIndexRouteImport.update({
  id: '/marriage/',
  path: '/marriage/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardContributionIndexRoute =
  DashboardContributionIndexRouteImport.update({
    id: '/contribution/',
    path: '/contribution/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardConfirmationIndexRoute =
  DashboardConfirmationIndexRouteImport.update({
    id: '/confirmation/',
    path: '/confirmation/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardCommunionIndexRoute = DashboardCommunionIndexRouteImport.update({
  id: '/communion/',
  path: '/communion/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardBaptismIndexRoute = DashboardBaptismIndexRouteImport.update({
  id: '/baptism/',
  path: '/baptism/',
  getParentRoute: () => DashboardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof _authLoginRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/baptism': typeof DashboardBaptismIndexRoute
  '/dashboard/communion': typeof DashboardCommunionIndexRoute
  '/dashboard/confirmation': typeof DashboardConfirmationIndexRoute
  '/dashboard/contribution': typeof DashboardContributionIndexRoute
  '/dashboard/marriage': typeof DashboardMarriageIndexRoute
  '/dashboard/members': typeof DashboardMembersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof _authLoginRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/baptism': typeof DashboardBaptismIndexRoute
  '/dashboard/communion': typeof DashboardCommunionIndexRoute
  '/dashboard/confirmation': typeof DashboardConfirmationIndexRoute
  '/dashboard/contribution': typeof DashboardContributionIndexRoute
  '/dashboard/marriage': typeof DashboardMarriageIndexRoute
  '/dashboard/members': typeof DashboardMembersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/__auth': typeof _authRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/__auth/login': typeof _authLoginRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/baptism/': typeof DashboardBaptismIndexRoute
  '/dashboard/communion/': typeof DashboardCommunionIndexRoute
  '/dashboard/confirmation/': typeof DashboardConfirmationIndexRoute
  '/dashboard/contribution/': typeof DashboardContributionIndexRoute
  '/dashboard/marriage/': typeof DashboardMarriageIndexRoute
  '/dashboard/members/': typeof DashboardMembersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/'
    | '/dashboard/baptism'
    | '/dashboard/communion'
    | '/dashboard/confirmation'
    | '/dashboard/contribution'
    | '/dashboard/marriage'
    | '/dashboard/members'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/dashboard/baptism'
    | '/dashboard/communion'
    | '/dashboard/confirmation'
    | '/dashboard/contribution'
    | '/dashboard/marriage'
    | '/dashboard/members'
  id:
    | '__root__'
    | '/'
    | '/__auth'
    | '/dashboard'
    | '/__auth/login'
    | '/dashboard/'
    | '/dashboard/baptism/'
    | '/dashboard/communion/'
    | '/dashboard/confirmation/'
    | '/dashboard/contribution/'
    | '/dashboard/marriage/'
    | '/dashboard/members/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  _authRouteRoute: typeof _authRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__auth': {
      id: '/__auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof _authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/__auth/login': {
      id: '/__auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof _authLoginRouteImport
      parentRoute: typeof _authRouteRoute
    }
    '/dashboard/members/': {
      id: '/dashboard/members/'
      path: '/members'
      fullPath: '/dashboard/members'
      preLoaderRoute: typeof DashboardMembersIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/marriage/': {
      id: '/dashboard/marriage/'
      path: '/marriage'
      fullPath: '/dashboard/marriage'
      preLoaderRoute: typeof DashboardMarriageIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/contribution/': {
      id: '/dashboard/contribution/'
      path: '/contribution'
      fullPath: '/dashboard/contribution'
      preLoaderRoute: typeof DashboardContributionIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/confirmation/': {
      id: '/dashboard/confirmation/'
      path: '/confirmation'
      fullPath: '/dashboard/confirmation'
      preLoaderRoute: typeof DashboardConfirmationIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/communion/': {
      id: '/dashboard/communion/'
      path: '/communion'
      fullPath: '/dashboard/communion'
      preLoaderRoute: typeof DashboardCommunionIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/baptism/': {
      id: '/dashboard/baptism/'
      path: '/baptism'
      fullPath: '/dashboard/baptism'
      preLoaderRoute: typeof DashboardBaptismIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface _authRouteRouteChildren {
  _authLoginRoute: typeof _authLoginRoute
}

const _authRouteRouteChildren: _authRouteRouteChildren = {
  _authLoginRoute: _authLoginRoute,
}

const _authRouteRouteWithChildren = _authRouteRoute._addFileChildren(
  _authRouteRouteChildren,
)

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardBaptismIndexRoute: typeof DashboardBaptismIndexRoute
  DashboardCommunionIndexRoute: typeof DashboardCommunionIndexRoute
  DashboardConfirmationIndexRoute: typeof DashboardConfirmationIndexRoute
  DashboardContributionIndexRoute: typeof DashboardContributionIndexRoute
  DashboardMarriageIndexRoute: typeof DashboardMarriageIndexRoute
  DashboardMembersIndexRoute: typeof DashboardMembersIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardBaptismIndexRoute: DashboardBaptismIndexRoute,
  DashboardCommunionIndexRoute: DashboardCommunionIndexRoute,
  DashboardConfirmationIndexRoute: DashboardConfirmationIndexRoute,
  DashboardContributionIndexRoute: DashboardContributionIndexRoute,
  DashboardMarriageIndexRoute: DashboardMarriageIndexRoute,
  DashboardMembersIndexRoute: DashboardMembersIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  _authRouteRoute: _authRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
